use soroban_sdk::contracterror;
use crate::prelude::*;

#[contracterror]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum GovernanceError {
    ProposalNotFound = 100,
    ProposalNotActive = 101,
    NotInVotingPeriod = 102,
    AlreadyVoted = 103,
    NoVotingPower = 104,
    InsufficientProposalPower = 105,
    VotingNotEnded = 106,
    InvalidProposalStatus = 107,
    ProposalExpired = 108,
    NotQueued = 109,
    InvalidExecutionTime = 110,
    ExecutionTooEarly = 111,
    AlreadyExecuted = 112,
    InvalidQuorum = 113,
    InvalidVotingPeriod = 114,
    CannotExecute = 115,
    QuorumNotMet = 116,
    ProposalDefeated = 117,
    InvalidAction = 118,
    ThresholdNotMet = 119,
    ProposalAlreadyFailed = 120,
    ProposalNotReady = 121,
    ExecutionFailed = 122,
    InvalidMultisigConfig = 123,
    InsufficientApprovals = 124,
    RecoveryInProgress = 125,
    NoRecoveryInProgress = 126,
    InvalidGuardianConfig = 127,
    GuardianAlreadyExists = 128,
    GuardianNotFound = 129,
    MathOverflow = 130,
    Unauthorized = 131,
    AlreadyInitialized = 132,
    NotInitialized = 133,
    InvalidProposal = 134,
    InvalidThreshold = 135,
    ProposalAlreadyExecuted = 136,
}
